[monitor:///var/log/suricata/eve. json]
disabled = false
index = suricata
sourcetype = suricata:json

[monitor:///var/log/suricata/fast. log]
disabled = false
index = suricata
sourcetype = suricata:fast

[monitor:///opt/zeek/logs/current]
disabled = false
index = zeek
sourcetype = bro:json

[monitor:///var/log/auth. log]
disabled = false
index = ubuntu-auth
sourcetype = linux_secure